#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? press and hold enabled/disabled for intellij
##?
##? Usage:
##?    dump-brew-pass
docs::parse "$@"

echo "no! use dot package"
