#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? It frees up space on the MacOS
##?
##? Usage:
##?    free-space
docs::parse "$@"

docker system prune -a
docker image prune -a
brew cleanup

echo "Rebooted."

