#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? it exposes the port used to authenticate when webapp opens a tunnel
##?
##? Usage:
##?    expose-ports-tunnel
docs::parse "$@"

devtools-expose-ports --container tef_api_login 18989
