#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Go to a specific O2DE page within webapp
##?
##? Usage:
##?    $o2de-pages
docs::parse "$@"

pushd ./ && cd $(grep -Ril --extended-regexp "O2De.+Agent" ./web/src/pages | sed -E "s/\.\/web\/src\/pages\/([^\/]+)\/.+\.ts[x]{0,1}/\1/g" | sed '$!N; /^\(.*\)\n\1$/!P; D' | sed 's/^/web\/src\/pages\//; s/$//' | fzf )