#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Launch the android emulator
##?
##? Usage:
##?    android-emulator <avd>
docs::parse "$@"

avd=$(echo "$1")

if [[ "${avd}" == "list" ]]; then
	~/Library/Android/sdk/emulator/emulator -list-avds
	exit 0
fi

~/Library/Android/sdk/emulator/emulator -avd ${1}
