#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Launch the android emulator
##?
##? Usage:
##?    android-emulator
docs::parse "$@"

/Users/mbertamini/Library/Android/sdk/emulator/emulator -avd Pixel_3a_API_33_arm64-v8a