#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Launch the android emulator
##?
##? Usage:
##?    android-emulator list
##?    android-emulator run <avd>
docs::parse "$@"

if [[ ${list} == true ]]; then
	~/Library/Android/sdk/emulator/emulator -list-avds
	exit 0
fi

avd=$(echo "$2")
~/Library/Android/sdk/emulator/emulator -avd ${avd}
